# Generated by Django 5.1.3 on 2024-12-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapped',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
