# Generated by Django 5.1.3 on 2024-12-01 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_wrapped_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapped',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_wrappeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
